### ISSUE TITLE
tweetbot support

### ISSUE THREAD

**Issue by Dreamersoul** [SwiftKitz/Appz#14]
i have found this on tweetbot official site [link](http://tapbots.net/tweetbot3/support/url-schemes/) it works on both tweetbot 3 and 4, even if we don't specify a screen name it would work too.
The issue is if i requested favourites and the favourites tab is hidden in the app it self then the favourites tab wouldn't show instead it would just open the app.
So should i implement it anyway, and if yes what should be the fall back url?

**Comment by Mazyod** [comment]
Apps that don't have a web counterpart can simply open the vendor's website for all actions if the app is not installed, in this case http://tapbots.com/tweetbot/. This makes sense because if the developer using Appz is trying to open Tweetbot, it means they really want the user to try Tweetbot.

As for the favorites note, we can simply open the app. It is the user's decision to hide the favorites for a good reason, probably, so opening the app shouldn't be an outrageous outcome.

Thanks!
