### ISSUE TITLE
Settings System ?

### ISSUE THREAD

**Issue by ngt14** [SwiftKitz/Appz#75]
Hello , it's possible to go on my Settings system with this plugin ? 
For example , in my app , i check if my wifi is activate, if my wifi is not activate , i want to go on Settings system (Android or Ios) to activate wifi . 
It's possible ?

**Comment by Mazyod** [comment]
Hello @jedofus,
Since this library is specifically targeted at iOS, I'll only cover that part. On iOS, there is no documented way to open Wifi settings from within the app, so we don't support that in Appz. If you are still interested in hacking together a solution, please see:

http://stackoverflow.com/a/33676848/456434
